server:
  port: 8080
  error:
    include-binding-errors: always

authorization:
  endpoints:
    - path: /users/all
      methods: # options: ["*", GET, POST, PUT, DELETE, HEAD, OPTIONS]
        - GET
      roles:
        - ADMIN
        - USER
    - path: /users/email/*
      methods: # options: ["*", GET, POST, PUT, DELETE, HEAD, OPTIONS]
        - GET
      roles:
        - ADMIN
        - USER
    - path: /users/**
      methods: # options: ["*", GET, POST, PUT, DELETE, HEAD, OPTIONS]
        - POST
        - PUT
        - DELETE
      roles:
        - ADMIN

springdoc:
  show-actuator: true
  writer-with-default-pretty-printer: true
  writer-with-order-by-keys: true
  swagger-ui:
    displayRequestDuration: true
    path: /swagger-ui
    url: /openapi.yml
    oauth:
      appName: spring-kotlin-user-auth-sql-datasource

spring:
  h2:
    console.enabled: true
  flyway:
    enabled: true
    locations: classpath:db/migration
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password: password
