name: Release

on:
  push:
    branches:
      - master

env:
  GITHUB_TOKEN: ${{ secrets.PAT }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.4.1
        with:
          access_token: ${{ env.GITHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"

      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Give Maven Wrapper permission to run
        run: sudo chmod -R a+rwx mvnw

      - name: Install semantic-release plugins
        run: npm install @semantic-release/git @conveyal/maven-semantic-release -D

      - name: Generate release
        run: npx semantic-release --prepare @conveyal/maven-semantic-release --verify-conditions @semantic-release/github,@conveyal/maven-semantic-release --verify-release @conveyal/maven-semantic-release --use-conveyal-workflow --skip-maven-deploy